import "./globals.css";
import { Inter } from 'next/font/google'
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ThemeProvider from "@/context/ThemeContext";

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '700']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
        <ThemeProvider>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
